---
- name: Add argocd chart repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"

- name: Deploy argocd
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: 8.1.3
    release_namespace: argocd
    create_namespace: true
    values: "{{ lookup('template', '../files/argocd.yaml') | from_yaml }}"
