#cloud-config
package_update: true
package_upgrade: true

#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 192.168.2.3/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 192.168.1.1
          - 8.8.8.8
          - 8.8.4.4

packages:
  - git
ansible:
  install_method: pip
  pull:
    url: "https://github.com/baptistedeporte/homelab.git"
    playbook_name: playbooks/k3s-node.yml
