- name: K3s Node Setup
  hosts: k3s_nodes
  become: yes
  roles:
    - common

  tasks:
    - name: Install K3s
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is running
      ansible.builtin.service:
        name: k3s
        state: started
        enabled: yes
