---
- name: Packages management
  hosts: server
  tasks:
    - name: Download Helm command line tool if needed
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        return_content: true
      register: helm_installer

    - name: Ensure Helm is installed
      ansible.builtin.command:
        cmd: bash
        stdin: "{{ helm_installer.content }}"
        creates: /usr/local/bin/helm
      environment:
        DESIRED_VERSION: "{{ helm_version | default('') }}"

    - name: Ensure Python is installed
      become: true
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present
