k3s_cluster:
  children:
    server:
      hosts:
        node-01:
          ansible_host: 192.168.2.3
          ansible_ssh_private_key_file: "./key"

  vars:
    ansible_port: 22
    ansible_user: ansible
    k3s_version: v1.30.2+k3s1
    # dummy value, need to use ansible vault
    token: "changeme!"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
